services:
  app:
    command: ["flask", "--app", "app", "run", "--debug", "--host=0.0.0.0", "--port=8000"]
    environment:
      FLASK_DEBUG: "1"
    volumes:
      - ./app:/app:ro
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile
