name: dive

on:
  push:
  pull_request:

jobs:
  dive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -f Dockerfile.bad -t hw-app:ci .

      - name: Check image with dive
        run: |
          docker run --rm -e CI=true \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD/.dive-ci:/.dive-ci:ro" \
            wagoodman/dive:latest hw-app:ci --ci-config /.dive-ci
